# Generated by Django 3.1.5 on 2021-01-27 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Concact',
            new_name='Contact',
        ),
    ]
