# Generated by Django 3.1.5 on 2021-02-18 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20210126_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='listing_id',
            field=models.CharField(max_length=100),
        ),
    ]
