# Generated by Django 3.1.5 on 2021-02-19 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_auto_20210217_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='prop_status',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
