# Generated by Django 3.1.5 on 2021-02-18 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='garage',
            new_name='beds',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='bathrooms',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='bedrooms',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='description',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='photo_1',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='photo_2',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='photo_3',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='photo_4',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='photo_5',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='photo_6',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='photo_main',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='realtor',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='zipcode',
        ),
        migrations.AddField(
            model_name='listing',
            name='baths',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
        migrations.AddField(
            model_name='listing',
            name='last_update',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='listing',
            name='lat',
            field=models.DecimalField(decimal_places=20, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='listing',
            name='listing_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='listing',
            name='lon',
            field=models.DecimalField(decimal_places=20, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='listing',
            name='neighborhood',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='listing',
            name='office_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='listing',
            name='photo',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='listing',
            name='postal_code',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='listing',
            name='price_raw',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='listing',
            name='prop_status',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='listing',
            name='prop_type',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='listing',
            name='rdc_web_url',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='listing',
            name='sqft_raw',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='listing',
            name='state_code',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='listing',
            name='address',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='listing',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='list_date',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='lot_size',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='sqft',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='state',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
