# Generated by Django 3.1.5 on 2021-02-19 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20210218_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='lat',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='listing',
            name='lon',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10),
        ),
    ]
