# Generated by Django 3.1.5 on 2021-02-19 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_remove_listing_lot_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='lot_size',
            field=models.CharField(default='', max_length=200),
        ),
    ]
