# Generated by Django 3.1.5 on 2021-02-19 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_auto_20210218_2142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='price_raw',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='sqft_raw',
        ),
    ]
