# Generated by Django 3.1.5 on 2021-02-19 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_auto_20210218_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='baths',
            field=models.CharField(default='', max_length=100),
        ),
    ]
